export interface Room {
    buildingId: string;
    roomNumber: string;
    capacity: number;
    type: string;
}

export const sampleRooms: Room[] = [
    { buildingId: "ASL", roomNumber: "107", capacity: 40, type: "Moveable Tablet Armchairs" },
    { buildingId: "ASL", roomNumber: "131", capacity: 72, type: "Group Share" },
    { buildingId: "ASL", roomNumber: "150", capacity: 195, type: "Theater" },
    { buildingId: "ARCH", roomNumber: "120", capacity: 130, type: "Theater" },
    { buildingId: "ARCH", roomNumber: "301", capacity: 21, type: "Movable Tables & Chairs" },
    { buildingId: "ARCH", roomNumber: "302", capacity: 53, type: "Theater" },
    { buildingId: "ARMRY", roomNumber: "101", capacity: 200, type: "Theater" },
    { buildingId: "ARMRY", roomNumber: "134", capacity: 35, type: "Gather" },
    { buildingId: "ARMRY", roomNumber: "136", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "137", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "143", capacity: 39, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "144", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "145", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "147", capacity: 46, type: "Theater" },
    { buildingId: "ARMRY", roomNumber: "148", capacity: 47, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "241", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "242", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "243", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "331", capacity: 60, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "333", capacity: 70, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "370", capacity: 46, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "384", capacity: 53, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "386", capacity: 53, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "428", capacity: 30, type: "Group Share" },
    { buildingId: "ARMRY", roomNumber: "429", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "430", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "432", capacity: 60, type: "Group Share" },
    { buildingId: "BEV", roomNumber: "103", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "108", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "132", capacity: 86, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "166", capacity: 72, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "180", capacity: 216, type: "Theater" },
    { buildingId: "BEV", roomNumber: "242", capacity: 43, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "393", capacity: 42, type: "Movable Tablet Armchairs" },
    { buildingId: "BUR", roomNumber: "124", capacity: 130, type: "Theater" },
    { buildingId: "CIF", roomNumber: "18", capacity: 36, type: "Group Share" },
    { buildingId: "CIF", roomNumber: "0027/1025", capacity: 483, type: "Theater" },
    { buildingId: "CIF", roomNumber: "35", capacity: 232, type: "Group Share" },
    { buildingId: "CIF", roomNumber: "36", capacity: 24, type: "Gather" },
    { buildingId: "CIF", roomNumber: "1035", capacity: 56, type: "Gather" },
    { buildingId: "CIF", roomNumber: "2018", capacity: 42, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "2025", capacity: 24, type: "Gather" },
    { buildingId: "CIF", roomNumber: "2035", capacity: 187, type: "Classroom-in-the-round" },
    { buildingId: "CIF", roomNumber: "2036", capacity: 40, type: "Gather" },
    { buildingId: "CIF", roomNumber: "2039", capacity: 72, type: "Gather" },
    { buildingId: "CIF", roomNumber: "3018", capacity: 42, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "3025", capacity: 80, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "3031", capacity: 174, type: "Tiered Pods" },
    { buildingId: "CIF", roomNumber: "3038", capacity: 40, type: "Gather" },
    { buildingId: "CIF", roomNumber: "3039", capacity: 300, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "4018", capacity: 36, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4025", capacity: 112, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "4029", capacity: 144, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4031", capacity: 90, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4035", capacity: 54, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4036", capacity: 36, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4039", capacity: 64, type: "Turn and Talk" },
    { buildingId: "CB", roomNumber: "214", capacity: 24, type: "Gather" },
    { buildingId: "CB", roomNumber: "218", capacity: 94, type: "Theater" },
    { buildingId: "CA", roomNumber: "1024", capacity: 137, type: "Theater" },
    { buildingId: "DH", roomNumber: "113", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "132", capacity: 34, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "136", capacity: 36, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "169", capacity: 36, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "212", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "214", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "215", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "312", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "313", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "329", capacity: 42, type: "Movable Tablet Armchairs" },
    { buildingId: "DH", roomNumber: "336", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "106", capacity: 29, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "108", capacity: 29, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "111", capacity: 29, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "113", capacity: 41, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "114", capacity: 271, type: "Theater" },
    { buildingId: "DKH", roomNumber: "115", capacity: 33, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "119", capacity: 65, type: "Theater" },
    { buildingId: "DKH", roomNumber: "123", capacity: 65, type: "Theater" },
    { buildingId: "DKH", roomNumber: "125", capacity: 41, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "206", capacity: 28, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "209", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "212", capacity: 27, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "215", capacity: 42, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "215B", capacity: 42, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "219", capacity: 27, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "222", capacity: 27, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "223", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "307", capacity: 31, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "310", capacity: 35, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "312", capacity: 35, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "317", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "322", capacity: 28, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "325", capacity: 35, type: "Movable Tablet Armchairs" },
    { buildingId: "DKH", roomNumber: "326", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "DCL", roomNumber: "1310", capacity: 100, type: "Theater" },
    { buildingId: "DCL", roomNumber: "1320", capacity: 200, type: "Tiered" },
    { buildingId: "EDUC", roomNumber: "2", capacity: 120, type: "Theater" },
    { buildingId: "EDUC", roomNumber: "37", capacity: 30, type: "Moveable Tables & Chairs" },
    { buildingId: "EDUC", roomNumber: "162", capacity: 43, type: "Movable Tablet Armchairs" },
    { buildingId: "EDUC", roomNumber: "166", capacity: 45, type: "Turn and Talk" },
    { buildingId: "EDUC", roomNumber: "323", capacity: 40, type: "Moveable Tables & Chairs" },
    { buildingId: "EDUC", roomNumber: "382", capacity: 25, type: "Moveable Tables & Chairs" },
    { buildingId: "EDUC", roomNumber: "385", capacity: 30, type: "Moveable Tables & Chairs" },
    { buildingId: "EDUC", roomNumber: "389", capacity: 23, type: "Moveable Tables & Chairs" },
    { buildingId: "EH", roomNumber: "106B1", capacity: 72, type: "Theater" },
    { buildingId: "EH", roomNumber: "106B3", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "EH", roomNumber: "106B6", capacity: 32, type: "Movable Tablet Armchairs" },
    { buildingId: "EH", roomNumber: "106B8", capacity: 72, type: "Theater" },
    { buildingId: "EB", roomNumber: "29", capacity: 24, type: "Gather" },
    { buildingId: "EB", roomNumber: "36", capacity: 29, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "44", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "69", capacity: 32, type: "Gather" },
    { buildingId: "EB", roomNumber: "104", capacity: 35, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "108", capacity: 46, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "113", capacity: 18, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "115", capacity: 25, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "119", capacity: 31, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "123", capacity: 18, type: "Moveable Tables & Chairs" },
    { buildingId: "EB", roomNumber: "125", capacity: 18, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "127", capacity: 23, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "131", capacity: 31, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "135", capacity: 18, type: "Moveable Tables & Chairs" },
    { buildingId: "EB", roomNumber: "149", capacity: 23, type: "Gather" },
    { buildingId: "EB", roomNumber: "150", capacity: 38, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "156", capacity: 21, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "160", capacity: 101, type: "Theater" },
    { buildingId: "EB", roomNumber: "259", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "303", capacity: 36, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "307", capacity: 14, type: "Movable Tablet Armchairs" },
    { buildingId: "EB", roomNumber: "309", capacity: 20, type: "Movable Tablet Armchairs" },
    { buildingId: "EVRT", roomNumber: "1302", capacity: 108, type: "Group Share" },
    { buildingId: "EVRT", roomNumber: "1306", capacity: 105, type: "Tiered Pods" },
    { buildingId: "EVRT", roomNumber: "2101", capacity: 63, type: "Group Share" },
    { buildingId: "EVRT", roomNumber: "2233", capacity: 72, type: "Gather" },
    { buildingId: "EVRT", roomNumber: "2310", capacity: 116, type: "Turn and Talk" },
    { buildingId: "EVRT", roomNumber: "3117", capacity: 44, type: "Gather" },
    { buildingId: "EVRT", roomNumber: "3217", capacity: 45, type: "Movable Tablet Armchairs" },
    { buildingId: "FA", roomNumber: "AUD", capacity: 750, type: "Theater" },
    { buildingId: "GH", roomNumber: "100", capacity: 218, type: "Theater" },
    { buildingId: "GH", roomNumber: "111", capacity: 38, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "112", capacity: 314, type: "Theater" },
    { buildingId: "GH", roomNumber: "205", capacity: 27, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "207", capacity: 25, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "213", capacity: 149, type: "Theater" },
    { buildingId: "GH", roomNumber: "215", capacity: 41, type: "Moveable Tables & Chairs" },
    { buildingId: "GH", roomNumber: "217", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "219", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "221", capacity: 25, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "223", capacity: 95, type: "Theater" },
    { buildingId: "GH", roomNumber: "307", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "311", capacity: 35, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "313", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "315", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "317", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "319", capacity: 94, type: "Theater" },
    { buildingId: "GH", roomNumber: "321", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "325", capacity: 17, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "327", capacity: 27, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "329", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "GH", roomNumber: "331", capacity: 27, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "137", capacity: 36, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "138", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "140", capacity: 36, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "142", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "143", capacity: 36, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "148", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "149", capacity: 36, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "152", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "154", capacity: 20, type: "Movable Tablet Armchairs" },
    { buildingId: "HAB", roomNumber: "156", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "HUFF", roomNumber: "112", capacity: 142, type: "Theater" },
    { buildingId: "HUFF", roomNumber: "209", capacity: 42, type: "Group Share" },
    { buildingId: "LIB", roomNumber: "66", capacity: 216, type: "Theater" },
    { buildingId: "LH", roomNumber: "1000", capacity: 113, type: "Theater" },
    { buildingId: "LH", roomNumber: "1002", capacity: 92, type: "Theater" },
    { buildingId: "LH", roomNumber: "1020", capacity: 16, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1022", capacity: 32, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1024", capacity: 28, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1026", capacity: 21, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1027", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1028", capacity: 32, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1051", capacity: 25, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1057", capacity: 25, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1060", capacity: 32, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1062", capacity: 21, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1064", capacity: 29, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1065", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1066", capacity: 32, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1068", capacity: 17, type: "Movable Tablet Armchairs" },
    { buildingId: "LH", roomNumber: "1090", capacity: 92, type: "Theater" },
    { buildingId: "LH", roomNumber: "1092", capacity: 113, type: "Theater" },
    { buildingId: "LH", roomNumber: "THEAT", capacity: 615, type: "Theater" },
    { buildingId: "LCLB", roomNumber: "1018", capacity: 13, type: "Moveable Tables & Chairs" },
    { buildingId: "LCLB", roomNumber: "1022", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1024", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1030", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1032", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1038", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1040", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1046", capacity: 14, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1048", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1110", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1112", capacity: 14, type: "Moveable Tables & Chairs" },
    { buildingId: "LCLB", roomNumber: "1118", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1120", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1126", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1128", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1134", capacity: 15, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1136", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "1140", capacity: 13, type: "Moveable Tables & Chairs" },
    { buildingId: "LCLB", roomNumber: "G18", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "G20", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "G24", capacity: 31, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "G30", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "G32", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "G36", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "G46", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "LCLB", roomNumber: "G48", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "LMS", roomNumber: "136", capacity: 54, type: "Gather" },
    { buildingId: "LMS", roomNumber: "137", capacity: 29, type: "Gather" },
    { buildingId: "LMS", roomNumber: "139", capacity: 29, type: "Gather" },
    { buildingId: "LMS", roomNumber: "141", capacity: 284, type: "Theater" },
    { buildingId: "LMS", roomNumber: "143", capacity: 29, type: "Gather" },
    { buildingId: "LMS", roomNumber: "144", capacity: 92, type: "Theater" },
    { buildingId: "LMS", roomNumber: "147", capacity: 30, type: "Moveable Tables & Chairs" },
    { buildingId: "LMS", roomNumber: "151", capacity: 202, type: "Theater" },
    { buildingId: "LMS", roomNumber: "158", capacity: 54, type: "Gather" },
    { buildingId: "MSEB", roomNumber: "100", capacity: 260, type: "Theater" },
    { buildingId: "MSEB", roomNumber: "119", capacity: 99, type: "Theater" },
    { buildingId: "MSEB", roomNumber: "305", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "MSEB", roomNumber: "4101", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "MSB", roomNumber: "274", capacity: 140, type: "Theater" },
    { buildingId: "MH", roomNumber: "103", capacity: 215, type: "Theater" },
    { buildingId: "MH", roomNumber: "313", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "MH", roomNumber: "320", capacity: 34, type: "Movable Tablet Armchairs" },
    { buildingId: "MH", roomNumber: "316N", capacity: 27, type: "Movable Tablet Armchairs" },
    { buildingId: "MH", roomNumber: "316S", capacity: 22, type: "Transitional" },
    { buildingId: "NSRC", roomNumber: "149", capacity: 245, type: "Theater" },
    { buildingId: "NHB", roomNumber: "2078", capacity: 38, type: "Gather" },
    { buildingId: "NHB", roomNumber: "2079", capacity: 312, type: "Theater" },
    { buildingId: "NOYES", roomNumber: "100", capacity: 342, type: "Theater" },
    { buildingId: "NOYES", roomNumber: "157", capacity: 68, type: "Turn and Talk" },
    { buildingId: "NOYES", roomNumber: "161", capacity: 82, type: "Theater" },
    { buildingId: "NOYES", roomNumber: "162", capacity: 33, type: "Movable Tablet Armchairs" },
    { buildingId: "NOYES", roomNumber: "163", capacity: 47, type: "Movable Tablet Armchairs" },
    { buildingId: "NOYES", roomNumber: "164", capacity: 32, type: "Transitional" },
    { buildingId: "NOYES", roomNumber: "165", capacity: 66, type: "Theater" },
    { buildingId: "NOYES", roomNumber: "203", capacity: 30, type: "Gather" },
    { buildingId: "NOYES", roomNumber: "204", capacity: 30, type: "Gather" },
    { buildingId: "NOYES", roomNumber: "217", capacity: 112, type: "Theater" },
    { buildingId: "NOYES", roomNumber: "300", capacity: 30, type: "Gather" },
    { buildingId: "NOYES", roomNumber: "301", capacity: 30, type: "Gather" },
    { buildingId: "NOYES", roomNumber: "303", capacity: 25, type: "Gather" },
    { buildingId: "NOYES", roomNumber: "304", capacity: 38, type: "Gather" },
    { buildingId: "PSYCH", roomNumber: "11", capacity: 30, type: "Group Share" },
    { buildingId: "PSYCH", roomNumber: "17", capacity: 48, type: "Moveable Tables & Chairs" },
    { buildingId: "PSYCH", roomNumber: "21", capacity: 24, type: "Movable Tablet Armchairs" },
    { buildingId: "PSYCH", roomNumber: "23", capacity: 155, type: "Theater" },
    { buildingId: "PSYCH", roomNumber: "29", capacity: 30, type: "Moveable Tables & Chairs" },
    { buildingId: "PSYCH", roomNumber: "31", capacity: 56, type: "Moveable Tables & Chairs" },
    { buildingId: "PSYCH", roomNumber: "32", capacity: 80, type: "Moveable Tables & Chairs" },
    { buildingId: "PSYCH", roomNumber: "207", capacity: 40, type: "Group Share" },
    { buildingId: "RAL", roomNumber: "116", capacity: 187, type: "Theater" },
    { buildingId: "LUMEB", roomNumber: "1043", capacity: 46, type: "Gather" },
    { buildingId: "LUMEB", roomNumber: "1047", capacity: 41, type: "Transitional" },
    { buildingId: "LUMEB", roomNumber: "2055", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "LUMEB", roomNumber: "2100", capacity: 144, type: "Moveable Tables & Chairs" },
    { buildingId: "LUMEB", roomNumber: "2200", capacity: 48, type: "Fixed Tables & Chairs" },
    { buildingId: "LUMEB", roomNumber: "3101", capacity: 72, type: "Moveable Tables & Chairs" },
    { buildingId: "SIEBL", roomNumber: "1302", capacity: 48, type: "Moveable Tables & Chairs" },
    { buildingId: "SIEBL", roomNumber: "1304", capacity: 46, type: "Moveable Tables & Chairs" },
    { buildingId: "SIEBL", roomNumber: "1404", capacity: 200, type: "Tiered" },
    { buildingId: "SHS", roomNumber: "110", capacity: 48, type: "Moveable Tables & Chairs" },
    { buildingId: "THBH", roomNumber: "134", capacity: 212, type: "Theater" },
    { buildingId: "TB", roomNumber: "101", capacity: 67, type: "Theater" },
    { buildingId: "TB", roomNumber: "103", capacity: 101, type: "Theater" },
    { buildingId: "TB", roomNumber: "112", capacity: 90, type: "Theater" },
    { buildingId: "TB", roomNumber: "114", capacity: 88, type: "Theater" },
    { buildingId: "TB", roomNumber: "203", capacity: 32, type: "Movable Tablet Armchairs" },
    { buildingId: "TB", roomNumber: "204", capacity: 25, type: "Movable Tablet Armchairs" },
    { buildingId: "TB", roomNumber: "206", capacity: 24, type: "Seminar Table & Moveable Chairs" },
    { buildingId: "TH", roomNumber: "W109", capacity: 90, type: "Fixed Tables & Moveable Chairs" },
    { buildingId: "TH", roomNumber: "W115", capacity: 40, type: "Moveable Tables & Chairs" },
    { buildingId: "TH", roomNumber: "W203", capacity: 48, type: "Moveable Tables & Chairs" },
    { buildingId: "WOHLR", roomNumber: "130", capacity: 46, type: "Tiered" },
    { buildingId: "WOHLR", roomNumber: "138", capacity: 20, type: "Fixed Tables & Chairs" },
    { buildingId: "WOHLR", roomNumber: "141", capacity: 306, type: "Theater" },
    { buildingId: "WOHLR", roomNumber: "152", capacity: 50, type: "Moveable Tables & Chairs" },
    { buildingId: "WOHLR", roomNumber: "166", capacity: 46, type: "Tiered" },
    { buildingId: "WOHLR", roomNumber: "170", capacity: 21, type: "Moveable Tables & Chairs" },
    { buildingId: "WOHLR", roomNumber: "174", capacity: 18, type: "Moveable Tables & Chairs" },
    { buildingId: "WOHLR", roomNumber: "226", capacity: 46, type: "Tiered" },
    { buildingId: "WOHLR", roomNumber: "236", capacity: 21, type: "Moveable Tables & Chairs" },
    { buildingId: "WOHLR", roomNumber: "241", capacity: 68, type: "Tiered" },
    { buildingId: "WOHLR", roomNumber: "243", capacity: 68, type: "Tiered" },
    { buildingId: "WOHLR", roomNumber: "245", capacity: 68, type: "Tiered" },
    { buildingId: "SWH", roomNumber: "1010", capacity: 60, type: "Unknown" },
    { buildingId: "SWH", roomNumber: "1020", capacity: 80, type: "Unknown" },
    { buildingId: "SWH", roomNumber: "1060", capacity: 60, type: "Unknown" },
    { buildingId: "SWH", roomNumber: "1100", capacity: 200, type: "Unknown" },
    { buildingId: "SWH", roomNumber: "2010", capacity: 60, type: "Unknown" },
    { buildingId: "SWH", roomNumber: "2020", capacity: 80, type: "Unknown" },
    { buildingId: "SWH", roomNumber: "2060", capacity: 60, type: "Unknown" },

];
