export interface Room {
    buildingId: string;
    roomNumber: string;
    capacity: number;
    type: string;
}

export const sampleRooms: Room[] = [
    { buildingId: "ASL", roomNumber: "107", capacity: 40, type: "Moveable Tablet Armchairs" },
    { buildingId: "ASL", roomNumber: "131", capacity: 72, type: "Group Share" },
    { buildingId: "ASL", roomNumber: "150", capacity: 195, type: "Theater" },
    { buildingId: "ARCH", roomNumber: "120", capacity: 130, type: "Theater" },
    { buildingId: "ARCH", roomNumber: "301", capacity: 21, type: "Movable Tables & Chairs" },
    { buildingId: "ARCH", roomNumber: "302", capacity: 53, type: "Theater" },
    { buildingId: "ARMRY", roomNumber: "101", capacity: 200, type: "Theater" },
    { buildingId: "ARMRY", roomNumber: "134", capacity: 35, type: "Gather" },
    { buildingId: "ARMRY", roomNumber: "136", capacity: 30, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "137", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "143", capacity: 39, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "144", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "145", capacity: 37, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "147", capacity: 46, type: "Theater" },
    { buildingId: "ARMRY", roomNumber: "148", capacity: 47, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "241", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "242", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "243", capacity: 26, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "331", capacity: 60, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "333", capacity: 70, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "370", capacity: 46, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "384", capacity: 53, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "386", capacity: 53, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "428", capacity: 30, type: "Group Share" },
    { buildingId: "ARMRY", roomNumber: "429", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "430", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "ARMRY", roomNumber: "432", capacity: 60, type: "Group Share" },
    { buildingId: "BEV", roomNumber: "103", capacity: 40, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "108", capacity: 48, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "132", capacity: 86, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "166", capacity: 72, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "180", capacity: 216, type: "Theater" },
    { buildingId: "BEV", roomNumber: "242", capacity: 43, type: "Movable Tablet Armchairs" },
    { buildingId: "BEV", roomNumber: "393", capacity: 42, type: "Movable Tablet Armchairs" },
    { buildingId: "BUR", roomNumber: "124", capacity: 130, type: "Theater" },
    { buildingId: "CIF", roomNumber: "18", capacity: 36, type: "Group Share" },
    { buildingId: "CIF", roomNumber: "0027/1025", capacity: 483, type: "Theater" },
    { buildingId: "CIF", roomNumber: "35", capacity: 232, type: "Group Share" },
    { buildingId: "CIF", roomNumber: "36", capacity: 24, type: "Gather" },
    { buildingId: "CIF", roomNumber: "1035", capacity: 56, type: "Gather" },
    { buildingId: "CIF", roomNumber: "2018", capacity: 42, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "2025", capacity: 24, type: "Gather" },
    { buildingId: "CIF", roomNumber: "2035", capacity: 187, type: "Classroom-in-the-round" },
    { buildingId: "CIF", roomNumber: "2036", capacity: 40, type: "Gather" },
    { buildingId: "CIF", roomNumber: "2039", capacity: 72, type: "Gather" },
    { buildingId: "CIF", roomNumber: "3018", capacity: 42, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "3025", capacity: 80, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "3031", capacity: 174, type: "Tiered Pods" },
    { buildingId: "CIF", roomNumber: "3038", capacity: 40, type: "Gather" },
    { buildingId: "CIF", roomNumber: "3039", capacity: 300, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "4018", capacity: 36, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4025", capacity: 112, type: "Turn and Talk" },
    { buildingId: "CIF", roomNumber: "4029", capacity: 144, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4031", capacity: 90, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4035", capacity: 54, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4036", capacity: 36, type: "Gather" },
    { buildingId: "CIF", roomNumber: "4039", capacity: 64, type: "Turn and Talk" },
    { buildingId: "CB", roomNumber: "214", capacity: 24, type: "Gather" },
    { buildingId: "CB", roomNumber: "218", capacity: 94, type: "Theater" },
    { buildingId: "CA", roomNumber: "1024", capacity: 137, type: "Theater" },
];
